apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcontribcol
  labels:
    app: otelcontribcol
data:
  config.yaml: |
    receivers:
      k8s_cluster:
        collection_interval: 60s
        node_conditions_to_report: [Ready, MemoryPressure]
      prometheus:
        config:
          global:
            scrape_interval: 30s
          scrape_configs:
            - job_name: otel-collector-cluster-receiver
              static_configs:
              - targets: [localhost:8888]
    processors:
      batch:
        send_batch_size: 1000
        timeout: 10s
    exporters:
      otlp:
        endpoint: ${OTEL_COLLECTOR_ENDPOINT}
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers: [k8s_cluster, prometheus]
          processors: [batch]
          exporters: [otlp]

