apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcontribcol
  labels:
    app: otelcontribcol
data:
  config.yaml: |
    receivers:
      k8s_cluster:
        collection_interval: 60s
        node_conditions_to_report: [Ready, MemoryPressure]
      kubeletstats:
        collection_interval: 60s
        auth_type: serviceAccount
        endpoint: ${K8S_NODE_NAME}:10250
        insecure_skip_verify: true
    processors:
      batch:
        send_batch_size: 1000
        timeout: 10s
    exporters:
      otlp:
        endpoint: ${OTEL_COLLECTOR_ENDPOINT}
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers: [k8s_cluster, kubeletstats]
          processors: [batch]
          exporters: [otlp]
