apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-agent
  labels:
    app: opentelemetry
    component: otel-collector-agent
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector-agent
  minReadySeconds: 5

  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector-agent
    spec:
      containers:
      - image: otel/opentelemetry-collector-contrib:0.45.0
        name: otel-collector-agent
        args:
          - "--config=/conf/otel-collector-config.yaml"
        env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: K8S_NAMESPACE
            valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: host.name=$(HOST_NAME)
          - name: OTEL_COLLECTOR_ENDPOINT
            value: my-release-signoz-otel-collector.platform.svc.cluster.local:4317
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
          - containerPort: 4317 # Default endpoint for OpenTelemetry GRPC receiver.
          - containerPort: 4318 # Default endpoint for OpenTelemetry HTTP receiver.
          - containerPort: 8888  # Default endpoint for internal metrics.
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
#        - name: otel-collector-secrets
#          mountPath: /secrets
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-collector-agent-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
      serviceAccountName: sa-otel-agent

#        - secret:
#            name: otel-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem
