apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-agent-conf
  labels:
    app: opentelemetry
    component: otel-collector-agent-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      # k8s_cluster:
      #   # auth_type: none
      #   node_conditions_to_report: [Ready, MemoryPressure]
      #   collection_interval: 10s
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu:
          load:
          memory:
          disk:
          filesystem:
          network:
      kubeletstats:
        collection_interval: 20s
        auth_type: "serviceAccount"
        endpoint: "${K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
    processors:
      batch:
        send_batch_size: 1000
        timeout: 10s
      resourcedetection:
        detectors: [env, eks, ec2]
        timeout: 2s


    extensions:
      health_check: {}
      zpages: {}
    exporters:
      otlp:
        endpoint: "<IP of mahcine hosting SigNoz>:4317"
        insecure: true
    service:
      extensions: [health_check, zpages]
      pipelines:
        metrics:
          receivers: [otlp, hostmetrics, kubeletstats]
          processors: [resourcedetection, batch]
          exporters: [otlp]