apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-agent-conf
  labels:
    app: opentelemetry
    component: otel-collector-agent-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      hostmetrics:
        collection_interval: 60s
        scrapers:
          cpu: {}
          load: {}
          memory: {}
          disk: {}
          filesystem: {}
          network: {}
      prometheus:
        config:
          global:
            scrape_interval: 30s
          scrape_configs:
            - job_name: otel-collector
              static_configs:
              - targets: [localhost:8888]
    processors:
      batch:
        send_batch_size: 1000
        timeout: 10s
      resourcedetection:
        detectors: [env, eks, ec2]
        timeout: 2s

    extensions:
      health_check: {}
      zpages: {}
    exporters:
      otlp:
        endpoint: ${OTEL_COLLECTOR_ENDPOINT}
        tls:
          insecure: true
    service:
      extensions: [health_check, zpages]
      pipelines:
        metrics:
          receivers: [otlp, hostmetrics, prometheus]
          processors: [resourcedetection, batch]
          exporters: [otlp]
