---
# create cwagent service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-otel-agent
  namespace: signoz-infra-metrics

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-otel-agent-role
  namespace: signoz-infra-metrics
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "endpoints"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes/stats", "configmaps", "events"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["otel-container-insight-clusterleader"]
    verbs: ["get","update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aoc-agent-role-binding
  namespace: signoz-infra-metrics
subjects:
  - kind: ServiceAccount
    name: sa-otel-agent
    namespace: signoz-infra-metrics

roleRef:
  kind: ClusterRole
  name: sa-otel-agent-role
  apiGroup: rbac.authorization.k8s.io